# Generated by Django 3.1.3 on 2020-11-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mypost',
            old_name='myfoact_created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='mypost',
            old_name='myfoact_publish_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='mypost',
            old_name='myfoact_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='mypost',
            old_name='myfoact_title',
            new_name='title',
        ),
    ]
