# Generated by Django 3.1.3 on 2020-11-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201115_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='created_date',
        ),
    ]
