# Generated by Django 3.1.3 on 2020-11-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
