# Generated by Django 3.1.3 on 2021-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mypost_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='publish_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
