# Generated by Django 3.1.3 on 2021-12-08 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211208_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='publish_date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 12, 8, 19, 46, 41, 809703, tzinfo=utc)),
        ),
    ]
