# Generated by Django 3.1.3 on 2021-12-11 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211208_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='publish_date',
            field=models.DateField(auto_created=True, default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='text',
            field=models.TextField(verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
