# Generated by Django 3.1.3 on 2021-12-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211211_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='photo',
            field=models.ImageField(blank=True, default='user_default_profile.png', null=True, upload_to='photo_blog/%Y/%m/%d'),
        ),
    ]
