# Generated by Django 3.1.3 on 2021-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211211_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='photo',
            field=models.ImageField(upload_to='photo_blog/%Y/%m/%d'),
        ),
    ]
