# Generated by Django 3.1.3 on 2021-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211211_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='photo',
            field=models.ImageField(default='user_default_profile.jpg', upload_to='photo_blog/%Y/%m/%d'),
        ),
    ]
