# Generated by Django 3.1.3 on 2022-01-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220116_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpage',
            old_name='comment',
            new_name='text',
        ),
    ]
